server:
  port: 1234
spring:
  datasource:
    password: Temp1234
    url: jdbc:mysql://localhost:3306/mydb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    
  application:
    name: coupon-service
    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
      
    

    
 